services:
  sam:
    build:
      context: .
      dockerfile: Dockerfile.sam
    volumes:
      - .:/sam
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /sam
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 2s
      retries: 10
    environment:
      - SAM_CLI_CONTAINER_CONNECTION_TIMEOUT=10
    command: >
      local start-api
      --host 0.0.0.0
      --container-host-interface 0.0.0.0
      --container-host ${CONTAINER_HOST}
      --docker-volume-basedir ${PROJECT_ROOT}
      --docker-network aws-sam-cli-bug-poc_default
      --skip-pull-image
      --debug
      --template child/template.yaml
      ${WARM_CONTAINERS_SWITCH}